apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: backend
type: Opaque
data:
  POSTGRES_USER: Y2l0aXppeF91c2Vy        # base64 encoded 'citizix_user'
  POSTGRES_PASSWORD: UzNjcmV0            # base64 encoded 'S3cret'
  POSTGRES_DB: Y2l0aXppeF9kYg==          # base64 encoded 'citizix_db'
