name: CI/CD Dev

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.vars.outputs.TAG }}
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag
        id: vars
        run: |
          BRANCH=$(echo "${GITHUB_REF_NAME}" | tr '/' '-')
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          echo "TAG=${BRANCH}-${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Build & Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ steps.vars.outputs.TAG }}

      - name: Build & Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ steps.vars.outputs.TAG }}

  deploy:
    needs: docker
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Update frontend image in manifest
        run: |
          TAG=${{ needs.docker.outputs.image-tag }}
          echo "Using tag: $TAG"
          sed -i "s|\(image:\s*\).*/frontend:latest|\1${{ secrets.DOCKERHUB_USERNAME }}/frontend:${TAG}|" k8s/frontend/frontend.yaml
          cat k8s/frontend/frontend.yaml

      - name: Update Backend image in manifest
        run: |
          TAG=${{ needs.docker.outputs.image-tag }}
          echo "Using tag: $TAG"
          sed -i "s|\(image:\s*\).*/backend:latest|\1${{ secrets.DOCKERHUB_USERNAME }}/backend:${TAG}|" k8s/backend/backend.yaml
          cat k8s/backend/backend.yaml

      - name: Apply manifest
        run: |
          export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
          kubectl apply -f k8s/frontend/frontend.yaml -n frontend
          kubectl apply -f k8s/backend/backend.yaml -n backend
